---
version: "2"
networks:
  default: ~
services:
  jobs:
    build:
      context: "."
    command: "bundle exec script/delayed_job run"
    networks:
      default:
        aliases:
          - jobs
  postgres:
    build: ./docker-compose/postgres
    networks:
      default:
        aliases:
          - postgres
  redis:
    image: "redis:alpine"
    networks:
      default:
        aliases:
          - redis
  web:
    build:
      context: "."
    networks:
      default:
        aliases:
          - web
